🔀:: clubmember api change
GSM-MSG/GCMS-iOS pull request #148
Opened 2023-02-07 10:13 UTC by minaje0917

## 개요
clubmember API를 API 명세서에 맞게 변경하였습니다.

## 작업사항
- clubAPI, clubMemberAPI 분리
- ClubMemberError 추가

## 변경로직

### 변경전

### 변경후

## 사용방법

## 기타

2023-02-07 10:16 UTC, baekteun requested changes

2023-02-07 10:16 UTC, baekteun commented on Service/Sources/Data/DataSource/Remote/API/ClubMemberAPI.swift
> +    }
lowerCamelCase에 맞게 해주세요

2023-02-07 10:18 UTC, baekteun requested changes

2023-02-07 10:18 UTC, baekteun commented on Service/Sources/Data/DataSource/Remote/API/ClubMemberAPI.swift
> +    }
switch case 작성하는 방식 스타일 가이드 맞춰주세요

2023-02-07 10:18 UTC, baekteun commented on Service/Sources/Data/DataSource/Remote/API/GCMSAPI.swift
> -    var errorMapper: [Int: GCMSError]? { get }
지우기보다 Int: Error로 해주세요

2023-02-07 10:18 UTC, baekteun commented on Service/Sources/Data/DataSource/Remote/DataMapping/Club/Member/MemberDTO.swift
> +        let scope: MemberScope
뭐죠 이 공백? 그리고 profileImg는 optional입니다

2023-02-07 10:24 UTC, minaje0917 commented on Service/Sources/Data/DataSource/Remote/API/ClubMemberAPI.swift
> +    }
수정하겠습니다

2023-02-07 10:29 UTC, minaje0917 commented on Service/Sources/Data/DataSource/Remote/API/ClubMemberAPI.swift
> +    }
수정하겠습니다.

2023-02-07 10:33 UTC, minaje0917 commented on Service/Sources/Data/DataSource/Remote/DataMapping/Club/Member/MemberDTO.swift
> +        let scope: MemberScope
수정하겠습니다

2023-02-07 10:34 UTC, minaje0917 commented on Service/Sources/Data/DataSource/Remote/API/GCMSAPI.swift
> -    var errorMapper: [Int: GCMSError]? { get }
수정하겠습니다.

2023-02-08 12:10 UTC, baekteun requested changes
UseCase도 변경필요합니다

2023-02-08 12:10 UTC, baekteun commented on Service/Sources/Data/Repositories/DefaultClubMemberRepository.swift
> +    private let clubLocal = ClubLocal.shared
??

2023-02-08 12:10 UTC, baekteun commented on Service/Sources/Data/Repositories/DefaultClubMemberRepository.swift
> +    private let clubLocal = ClubLocal.shared
쓰지않는 거면 그냥 제거하는게 좋을거같아요

2023-02-08 12:25 UTC, minaje0917 commented on Service/Sources/Data/Repositories/DefaultClubMemberRepository.swift
> +    private let clubLocal = ClubLocal.shared
수정하겠습니다

2023-02-08 15:03 UTC, baekteun commented on Service/Sources/Data/DataSource/Remote/API/AuthAPI.swift
> +    var errorMapper: [Int : Error]? {
스타일 가이드 맞춰서 [Int: Error]? 로 해주세요

2023-02-08 15:03 UTC, baekteun commented on Service/Sources/Data/DataSource/Remote/API/AuthAPI.swift
> +
이쪽 공백 빼줘요

2023-02-08 15:03 UTC, baekteun commented on Service/Sources/Data/DataSource/Remote/API/ClubMemberAPI.swift
> +
이익

2023-02-08 15:03 UTC, baekteun commented on Service/Sources/Data/DataSource/Remote/API/ClubMemberAPI.swift
> +    var errorMapper: [Int : Error]? {
[Int: Error]?

2023-02-08 15:11 UTC, minaje0917 commented on Service/Sources/Data/DataSource/Remote/API/AuthAPI.swift
> +    var errorMapper: [Int : Error]? {
수정하겠습니다.

2023-02-08 15:11 UTC, minaje0917 commented on Service/Sources/Data/DataSource/Remote/API/AuthAPI.swift
> +
수정하겠습니다.

2023-02-08 15:11 UTC, minaje0917 commented on Service/Sources/Data/DataSource/Remote/API/ClubMemberAPI.swift
> +
수정하겠습니다.

2023-02-08 15:58 UTC, kimsh153 requested changes

2023-02-08 15:58 UTC, kimsh153 commented on Service/Sources/Data/DataSource/Remote/API/ClubMemberAPI.swift
> +                400: ClubMemberError.kickMyself,
kickMySelf는 강퇴하는 경우의 에러 아닌가요? 여기는 delegationMySelf 에러가 들어가야 하지 않을까요?

2023-02-08 15:58 UTC, kimsh153 commented on Service/Sources/Data/DataSource/Remote/API/ClubMemberAPI.swift
> +            ]
400에러인 kickMySelf가 없는거 같습니다

2023-02-08 16:28 UTC, minaje0917 commented on Service/Sources/Data/DataSource/Remote/API/ClubMemberAPI.swift
> +                400: ClubMemberError.kickMyself,
수정하겠습니다.

2023-02-08 16:28 UTC, minaje0917 commented on Service/Sources/Data/DataSource/Remote/API/ClubMemberAPI.swift
> +            ]
수정하겠습니다.

2023-02-09 02:41 UTC, baekteun approved these changes

2023-02-09 05:35 UTC, kimsh153 approved these changes

2023-02-09 07:58 UTC, merged