🔀:: club api change
GSM-MSG/GCMS-iOS pull request #155
Opened 2023-02-11 04:59 UTC by minaje0917

## 개요
Club을 API 명세서에 맞게 수정

## 작업사항
- clubAPI API 명세서에 맞게 수정
- ClubRemote API 명세서에 맞게 수정
- ClubRepository API 명세서에 맞게 수정
- DefaultClubRepository API 명세서에 맞게 수정
- ClubRequest API 명세서에 맞게 수정

## 변경로직

### 변경전

### 변경후

## 사용방법

## 기타

2023-02-11 05:00 UTC, baekteun requested changes

2023-02-11 05:00 UTC, baekteun commented on Service/Sources/Data/DataSource/Remote/API/ClubAPI.swift
> +    case exitClub(clubID: String)
club ID는.. Long타입인데요?

2023-02-11 05:44 UTC, minaje0917 commented on Service/Sources/Data/DataSource/Remote/API/ClubAPI.swift
> +    case exitClub(clubID: String)
수정하겠습니다.

2023-02-13 05:14 UTC, baekteun approved these changes
주석된부분 해제 ㄱㄱ

2023-02-13 09:02 UTC, kimsh153 approved these changes

2023-02-13 09:05 UTC, merged