🔀 :: ViewController, Reactor Activity Indicator
GSM-MSG/GCMS-iOS pull request #23
Opened 2022-03-09 06:27 UTC by baekteun

전페이지에 Indicator binding 및 state 추가

2022-03-09 06:28 UTC, chanwoo00106 commented
let을 많이 쓰는데 const도 사용해 주세요

2022-03-09 06:29 UTC, baekteun commented
> let을 많이 쓰는데 const도 사용해 주세요

미쳤어요?

2022-03-09 06:38 UTC, chanwoo00106 requested changes
const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const

2022-03-09 06:39 UTC, chanwoo00106 commented
![image](https://user-images.githubusercontent.com/57276315/157386379-3d12cd5b-3688-4586-a0cd-5f9e2c951933.png)

2022-03-09 06:41 UTC, chanwoo00106 commented
![image](https://user-images.githubusercontent.com/57276315/157386516-d0334e76-35c7-4ae3-87ca-6003d1420db0.png)
재밌다

2022-03-09 06:42 UTC, chanwoo00106 commented
https://nextjs.org/

2022-03-09 06:43 UTC, chanwoo00106 commented
그만좀 지워

2022-03-09 06:47 UTC, chanwoo00106 commented
https://www.google.com/search?q=ios+%EA%B0%80+%EC%93%B0%EB%A0%88%EA%B8%B0%EC%9D%B8+%EC%9D%B4%EC%9C%A0&oq=ios+%EA%B0%80+%EC%93%B0%EB%A0%88%EA%B8%B0%EC%9D%B8+%EC%9D%B4%EC%9C%A0&aqs=chrome..69i57.7651j0j7&sourceid=chrome&ie=UTF-8

2022-03-09 06:48 UTC, chanwoo00106 commented
![대충 ios가 좋다는 사이트(?)](https://www.google.com/search?q=ios+%EA%B0%80+%EC%93%B0%EB%A0%88%EA%B8%B0%EC%9D%B8+%EC%9D%B4%EC%9C%A0&oq=ios+%EA%B0%80+%EC%93%B0%EB%A0%88%EA%B8%B0%EC%9D%B8+%EC%9D%B4%EC%9C%A0&aqs=chrome..69i57.7651j0j7&sourceid=chrome&ie=UTF-8)

2022-03-09 06:48 UTC, chanwoo00106 commented
잘못 보냈는데...

2022-03-09 06:49 UTC, chanwoo00106 commented
지우지 말아주세요

2022-03-09 06:51 UTC, chanwoo00106 commented
:ts: :thumbsup:

2022-03-09 06:51 UTC, chanwoo00106 commented
typescript 이모지가 있었으면...

2022-03-09 23:24 UTC, chanwoo00106 commented
c

2022-03-09 23:24 UTC, chanwoo00106 commented
o

2022-03-09 23:24 UTC, chanwoo00106 commented
n

2022-03-09 23:25 UTC, chanwoo00106 commented
s

2022-03-09 23:25 UTC, chanwoo00106 commented
t

2022-03-09 23:25 UTC, chanwoo00106 commented
let이 너무 많군요
const를 사용해주세요

2022-03-10 00:36 UTC, chanwoo00106 commented
const가 default 입니다

2022-03-10 01:33 UTC, closed without merging