🔀 :: API DI
GSM-MSG/GCMS-iOS pull request #71
Opened 2022-04-28 06:53 UTC by baekteun

## 개요
각 Reactor에 DI

## 작업사항
모든 Reactor에 UseCase Injection

2022-04-28 07:00 UTC, kimsh153 requested changes
LGTM

2022-04-28 07:02 UTC, baekteun commented on Service/Sources/Data/DataSource/Remote/DataSource/BaseRemote.swift
> +    private let provider = MoyaProvider<API>(plugins: [JWTPlugin(), NetworkLoggerPlugin()])
"느려." [1edbe6](https://github.com/GSM-MSG/GCMS-iOS/pull/71/commits/1edbe6251a4a47dd5161098855ce8876a4f3b3a1)

2022-04-28 07:12 UTC, kimsh153 requested changes

2022-04-28 07:12 UTC, kimsh153 commented on iOS/Sources/Presentation/Scene/Main/DetailClub/View/HeaderLabel.swift
> +    }
바꿔

2022-04-28 07:15 UTC, baekteun commented on iOS/Sources/Presentation/Scene/Main/DetailClub/View/HeaderLabel.swift
> +    }
수정! [943a18](https://github.com/GSM-MSG/GCMS-iOS/pull/71/commits/943a18c53427cf6f27528673f46be47200531227)

2022-04-28 07:17 UTC, chanwoo00106 approved these changes
어디선가 들려오는 pr의 소리
잘 먹겠습니다

2022-04-28 07:17 UTC, khs3994 approved these changes

2022-04-28 07:53 UTC, kimsh153 approved these changes
LGTM

2022-04-29 05:26 UTC, kimsh153 approved these changes

2022-04-29 05:46 UTC, yoonjibin approved these changes

2022-04-30 09:27 UTC, Huuuunee approved these changes

2022-04-30 10:55 UTC, khs3994 approved these changes

2022-05-03 13:32 UTC, merged